#!/bin/bash

# This script was generated by ChatGPT for convenience.

# Function to escape special characters for sed
escape_for_sed() {
    echo "$1" | sed -e 's/[]\/$*.^[]/\\&/g'
}

# Check for correct number of arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <directory> <search_string> <replace_string>"
    exit 1
fi

# Assigning arguments to variables
DIRECTORY=$1
SEARCH_STRING=$(escape_for_sed "$2")
REPLACE_STRING=$3

# Checking if the specified directory exists
if [ ! -d "$DIRECTORY" ]; then
    echo "Directory does not exist: $DIRECTORY"
    exit 1
fi

# Find and Replace
find "$DIRECTORY" -type f -exec sed -i "s/$SEARCH_STRING/$REPLACE_STRING/g" {} +

echo "Replacement complete."
